// Renders docs/preview.html: each demo email next to the draft the script would create,
// using the recorded Gemini answers. A local picture of the output, not a Gmail screenshot.
// Usage: node scripts/preview.js [out-name] [fixture ids...]
const fs = require('node:fs');
const path = require('node:path');
const { loadGas, recorded } = require('../test/gas.js');

const gas = loadGas();
const rows = gas.rateRowsFromTable(gas.DEMO_RATES);
const settings = { signerName: gas.DEMO_BROKER, companyName: gas.DEMO_COMPANY };
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const mark = (s) => esc(s).replace(/\[RATE:[^\]]*\]/g, (m) => `<mark>${m}</mark>`).replace(/\$[\d,]+ all-in/g, (m) => `<b>${m}</b>`);

const [outName = 'preview', ...ids] = process.argv.slice(2);
const cards = gas.DEMO_EMAILS.filter((e) => !ids.length || ids.includes(e.id)).map((e) => {
  const plan = gas.planReply(e.messages, recorded(e.id), rows, settings);
  const thread = e.messages.map((m) => `<div class="msg${m.isMine ? ' mine' : ''}"><div class="from">${esc(m.isMine ? 'You' : m.from)}</div><pre>${esc(gas.stripQuoted(m.body))}</pre></div>`).join('');
  const right = plan.action === 'skip'
    ? '<div class="label skip">Not a quote</div><p class="none">No draft. Left for a person.</p>'
    : `<div class="label">Quote ready</div><pre class="draft">${mark(plan.body)}</pre>`;
  return `<section><div class="col"><h2>${esc(e.subject)}</h2>${thread}</div><div class="col">${right}</div></section>`;
}).join('\n');

const html = `<!doctype html><meta charset="utf-8"><title>Quote drafts: local preview</title>
<style>
body{font:14px/1.45 system-ui,sans-serif;background:#f4f5f7;color:#1d2330;margin:0;padding:24px}
h1{font-size:20px;margin:0 0 4px}p.sub{margin:0 0 20px;color:#5b6475}
section{display:grid;grid-template-columns:1fr 1fr;gap:16px;background:#fff;border:1px solid #dde1e8;border-radius:8px;padding:16px;margin-bottom:14px}
h2{font-size:15px;margin:0 0 8px}.from{font-weight:600;font-size:13px;color:#3a4356}
.msg{border-left:3px solid #c9ced8;padding:4px 10px;margin-bottom:8px}.msg.mine{border-color:#8fb3e8;background:#f5f8fd}
pre{white-space:pre-wrap;font:inherit;margin:4px 0 0}
.draft{background:#fffdf3;border:1px dashed #d9c77a;border-radius:6px;padding:10px}
.label{display:inline-block;background:#1f7a4d;color:#fff;font-size:12px;border-radius:4px;padding:2px 8px;margin-bottom:6px}
.label.skip{background:#6b7280}.none{color:#5b6475}mark{background:#ffe08a}
@media(max-width:800px){section{grid-template-columns:1fr}}
</style>
<h1>Quote drafts: local preview</h1>
<p class="sub">Left: the email that came in. Right: the draft reply saved in the same thread. Nothing is sent. Yellow = the broker fills this in. Generated by <code>node scripts/preview.js</code> from the recorded Gemini answers.</p>
${cards}`;

const out = path.join(__dirname, '..', 'docs', outName + '.html');
fs.writeFileSync(out, html);
console.log('wrote ' + out);
